server:
   port: 8888
logging:
    path: logs
    file: sdk.log

#   测试环境：java -jar SDK-Server-1.0-SNAPSHOT.jar --spring.profiles.active=test
#   生产环境：java -jar SDK-Server-1.0-SNAPSHOT.jar --spring.profiles.active=prod



spring:
   application:
          name: sdk
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://10.100.46.162:8806/SDK
       username: admin
       password: 123456

mybatis:
    type-aliases-package: com.baidu.ocrqa.sdk.model
    mapper-locations:
       - mapper/*
file:
    #SDK调用识别结果存储路径
    path: /workspace/eval/result/
    # 项目上传文件保存路径
    project-file-save-path: /workspace/baidu/
    project-download-path: /projectFile/
    project-absolute-path: /workspace/apache-tomcat-9.0.2/webapps/ROOT/projectFile/
eval:
    general:
        no-position:
            script: /workspace/eval/scriptAndGt/eval_noposition.py
            gt:
                fengchao: /workspace/eval/scriptAndGt/fengchaogt
                yinshua:
                timu:
                mix2923general:
                kuaishou:

        with-position:
            script: /workspace/eval/scriptAndGt/ocr_eval_word
            gt:
                fengchao: /workspace/eval/scriptAndGt/fengchaoWithPosition
                yinshua:
                timu:
                mix2923general:
                kuaishou:

    idcard:
        front:
#  运行命令  python idcard_evaluator.py --format kv result gt
            script: /workspace/eval/scriptAndGt/idcard_evaluator.py
            gt:
                qianbao-idcard-front: /workspace/eval/scriptAndGt/idcardgt1
                qianbao-idcard-front-update:
        back:
            script: /workspace/eval/scriptAndGt/idcard_evaluator.py
            gt:
                qianbao-idcard-back: /workspace/eval/scriptAndGt/idcard-gt-back1


image:
    path:
        function:
            general: /sdkimg/function/general/001.jpg
            idcard:
                front:
                back:
        performance:
            general: /sdkimg/performance/general/performance_500.zip
            idcard:
                front:
                back:
        stability:
            general: /sdkimg/stability/general/stability_500.zip
            idcard:
                front:
                back:
        eval:
            general:
                withPosition:
                noPosition:
            idcard:
                front:
                back:
    host: http://localhost:8088

